-- ============================================================================
-- V12 — Historical Data Migration Staging Tables
-- ============================================================================
-- Adds four isolated staging tables for digitizing paper records.
-- No existing tables are modified.
-- Data flows:  UPLOADED -> OCR -> EXTRACT -> REVIEW -> VERIFIED -> IMPORTED
-- Only after VERIFIED does any data touch production customer/order tables.
--
-- NOTE: Uses TIMESTAMP WITH TIME ZONE (SQL standard) instead of TIMESTAMPTZ
-- (PostgreSQL alias) so this script is also compatible with H2 in dev mode.
-- ============================================================================

-- ── 1. migration_batches ─────────────────────────────────────────────────────
-- Groups a set of scanned documents from the same year and branch.

CREATE TABLE migration_batches (
    id               BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code       VARCHAR(30)     NOT NULL UNIQUE,     -- e.g. BATCH-2023-CBE-001
    branch_id        BIGINT          REFERENCES branches(id) ON DELETE RESTRICT,
    description      VARCHAR(255),
    source_year      SMALLINT        NOT NULL,             -- e.g. 2022
    -- counters (updated atomically as documents progress)
    total_documents  INTEGER         NOT NULL DEFAULT 0,
    uploaded_count   INTEGER         NOT NULL DEFAULT 0,
    processed_count  INTEGER         NOT NULL DEFAULT 0,
    reviewed_count   INTEGER         NOT NULL DEFAULT 0,
    approved_count   INTEGER         NOT NULL DEFAULT 0,
    imported_count   INTEGER         NOT NULL DEFAULT 0,
    failed_count     INTEGER         NOT NULL DEFAULT 0,
    -- status
    status           VARCHAR(30)     NOT NULL DEFAULT 'OPEN',  -- OPEN | COMPLETED | CLOSED
    -- audit
    created_by       BIGINT          REFERENCES employees(id) ON DELETE SET NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    completed_at     TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_migration_batches_branch    ON migration_batches(branch_id);
CREATE INDEX idx_migration_batches_status    ON migration_batches(status);
CREATE INDEX idx_migration_batches_year      ON migration_batches(source_year);

-- ── 2. migration_documents ───────────────────────────────────────────────────
-- One row per scanned paper image or PDF page.

CREATE TABLE migration_documents (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id             BIGINT          NOT NULL REFERENCES migration_batches(id) ON DELETE CASCADE,
    document_code        VARCHAR(40)     NOT NULL UNIQUE,   -- HIST-2023-CBE-000001
    file_name            VARCHAR(255)    NOT NULL,
    file_path            VARCHAR(1000)   NOT NULL,          -- absolute path on server disk
    file_type            VARCHAR(10)     NOT NULL,          -- IMAGE | PDF
    source_year          SMALLINT        NOT NULL,

    -- pipeline status columns (each updated independently)
    ocr_status           VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
    extraction_status    VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
    review_status        VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
    import_status        VARCHAR(30)     NOT NULL DEFAULT 'PENDING',

    -- OCR output
    raw_ocr_text         TEXT,
    ocr_confidence       DECIMAL(5, 2),                     -- 0.00 - 100.00

    -- extraction output
    extracted_data_json  TEXT,                              -- JSON: ExtractedData

    -- reviewer corrections (most recent)
    corrected_data_json  TEXT,                              -- JSON: corrected ExtractedData

    -- error tracking
    error_message        VARCHAR(1000),

    -- audit
    created_by           BIGINT          REFERENCES employees(id) ON DELETE SET NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_migration_documents_batch         ON migration_documents(batch_id);
CREATE INDEX idx_migration_documents_ocr_status    ON migration_documents(ocr_status);
CREATE INDEX idx_migration_documents_review_status ON migration_documents(review_status);
CREATE INDEX idx_migration_documents_import_status ON migration_documents(import_status);

-- ── 3. migration_reviews ─────────────────────────────────────────────────────
-- Records every human review action (one row per review pass per document).

CREATE TABLE migration_reviews (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id          BIGINT          NOT NULL REFERENCES migration_documents(id) ON DELETE CASCADE,
    reviewer_id          BIGINT          REFERENCES employees(id) ON DELETE SET NULL,
    review_status        VARCHAR(30)     NOT NULL,          -- APPROVED | REJECTED | NEEDS_REWORK
    corrected_data_json  TEXT,                              -- JSON: what the reviewer changed
    remarks              VARCHAR(1000),
    reviewed_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_migration_reviews_document    ON migration_reviews(document_id);
CREATE INDEX idx_migration_reviews_reviewer    ON migration_reviews(reviewer_id);

-- ── 4. migration_imports ─────────────────────────────────────────────────────
-- Full audit trail of what was created in production ERP tables from each document.

CREATE TABLE migration_imports (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id          BIGINT          NOT NULL REFERENCES migration_documents(id) ON DELETE RESTRICT,
    -- links to production records created
    customer_mobile      VARCHAR(15)     REFERENCES customers(customer_mobile) ON DELETE SET NULL,
    order_id             BIGINT          REFERENCES customer_orders(id) ON DELETE SET NULL,
    measurement_id       BIGINT          REFERENCES order_measurements(id) ON DELETE SET NULL,
    -- outcome
    import_status        VARCHAR(30)     NOT NULL,          -- IMPORTED | IMPORT_FAILED | DUPLICATE
    error_message        VARCHAR(1000),
    -- audit
    imported_by          BIGINT          REFERENCES employees(id) ON DELETE SET NULL,
    imported_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_migration_imports_document    ON migration_imports(document_id);
CREATE INDEX idx_migration_imports_customer    ON migration_imports(customer_mobile);
CREATE INDEX idx_migration_imports_order       ON migration_imports(order_id);
