-- ============================================================================
-- V16 — Re-create Historical Data Migration Staging Tables
-- ============================================================================
-- Restores the staging tables dropped in V15 so historical data migration
-- is fully functional and Hibernate schema validation passes cleanly.
-- Compatible with PostgreSQL and H2.
-- ============================================================================

-- ── 1. migration_batches ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS migration_batches (
    id               BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code       VARCHAR(30)     NOT NULL UNIQUE,
    branch_id        BIGINT          REFERENCES branches(id) ON DELETE RESTRICT,
    description      VARCHAR(255),
    source_year      SMALLINT        NOT NULL,
    total_documents  INTEGER         NOT NULL DEFAULT 0,
    uploaded_count   INTEGER         NOT NULL DEFAULT 0,
    processed_count  INTEGER         NOT NULL DEFAULT 0,
    reviewed_count   INTEGER         NOT NULL DEFAULT 0,
    approved_count   INTEGER         NOT NULL DEFAULT 0,
    imported_count   INTEGER         NOT NULL DEFAULT 0,
    failed_count     INTEGER         NOT NULL DEFAULT 0,
    status           VARCHAR(30)     NOT NULL DEFAULT 'OPEN',
    created_by       BIGINT          REFERENCES employees(id) ON DELETE SET NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    completed_at     TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_migration_batches_branch    ON migration_batches(branch_id);
CREATE INDEX IF NOT EXISTS idx_migration_batches_status    ON migration_batches(status);
CREATE INDEX IF NOT EXISTS idx_migration_batches_year      ON migration_batches(source_year);

-- ── 2. migration_documents ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS migration_documents (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id             BIGINT          NOT NULL REFERENCES migration_batches(id) ON DELETE CASCADE,
    document_code        VARCHAR(40)     NOT NULL UNIQUE,
    file_name            VARCHAR(255)    NOT NULL,
    file_path            VARCHAR(1000)   NOT NULL,
    file_type            VARCHAR(10)     NOT NULL,
    source_year          SMALLINT        NOT NULL,

    ocr_status           VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
    extraction_status    VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
    review_status        VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
    import_status        VARCHAR(30)     NOT NULL DEFAULT 'PENDING',

    raw_ocr_text         TEXT,
    ocr_confidence       DECIMAL(5, 2),

    extracted_data_json  TEXT,
    corrected_data_json  TEXT,
    error_message        VARCHAR(1000),

    created_by           BIGINT          REFERENCES employees(id) ON DELETE SET NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Multi-page PDF support
    page_number          INTEGER         NOT NULL DEFAULT 1,
    total_pages          INTEGER         NOT NULL DEFAULT 1,
    source_file_name     VARCHAR(255),
    source_file_path     VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_migration_documents_batch         ON migration_documents(batch_id);
CREATE INDEX IF NOT EXISTS idx_migration_documents_ocr_status    ON migration_documents(ocr_status);
CREATE INDEX IF NOT EXISTS idx_migration_documents_review_status ON migration_documents(review_status);
CREATE INDEX IF NOT EXISTS idx_migration_documents_import_status ON migration_documents(import_status);
CREATE INDEX IF NOT EXISTS idx_migration_documents_source_file   ON migration_documents(source_file_name);
CREATE INDEX IF NOT EXISTS idx_migration_documents_page_num     ON migration_documents(page_number);
CREATE INDEX IF NOT EXISTS idx_migration_documents_batch_page    ON migration_documents(batch_id, page_number);

-- ── 3. migration_reviews ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS migration_reviews (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id          BIGINT          NOT NULL REFERENCES migration_documents(id) ON DELETE CASCADE,
    reviewer_id          BIGINT          REFERENCES employees(id) ON DELETE SET NULL,
    review_status        VARCHAR(30)     NOT NULL,
    corrected_data_json  TEXT,
    remarks              VARCHAR(1000),
    reviewed_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_migration_reviews_document    ON migration_reviews(document_id);
CREATE INDEX IF NOT EXISTS idx_migration_reviews_reviewer    ON migration_reviews(reviewer_id);

-- ── 4. migration_imports ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS migration_imports (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id          BIGINT          NOT NULL REFERENCES migration_documents(id) ON DELETE RESTRICT,
    customer_mobile      VARCHAR(15)     REFERENCES customers(customer_mobile) ON DELETE SET NULL,
    order_id             BIGINT          REFERENCES customer_orders(id) ON DELETE SET NULL,
    measurement_id       BIGINT          REFERENCES order_measurements(id) ON DELETE SET NULL,
    import_status        VARCHAR(30)     NOT NULL,
    error_message        VARCHAR(1000),
    imported_by          BIGINT          REFERENCES employees(id) ON DELETE SET NULL,
    imported_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_migration_imports_document    ON migration_imports(document_id);
CREATE INDEX IF NOT EXISTS idx_migration_imports_customer    ON migration_imports(customer_mobile);
CREATE INDEX IF NOT EXISTS idx_migration_imports_order       ON migration_imports(order_id);
